// <auto-generated />
using System;
using BridgeITAPIs.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BridgeITAPIs.Migrations
{
    [DbContext(typeof(BridgeItContext))]
    [Migration("20260126111308_otpToUserEntity")]
    partial class otpToUserEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BridgeITAPIs.Models.BoughtFyp", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<byte[]>("Agreement")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("agreement");

                    b.Property<Guid?>("FypId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fyp_id");

                    b.Property<Guid?>("IndExpertId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ind_expert_id");

                    b.Property<long?>("Price")
                        .HasColumnType("bigint")
                        .HasColumnName("price");

                    b.Property<DateOnly?>("PurchaseDate")
                        .HasColumnType("date")
                        .HasColumnName("purchase_date");

                    b.Property<Guid?>("UniversityAdminId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("university_admin_id");

                    b.HasKey("Id")
                        .HasName("PK__BoughtFY__3213E83FCEA1BCAA");

                    b.HasIndex("FypId");

                    b.HasIndex("IndExpertId");

                    b.HasIndex("UniversityAdminId");

                    b.ToTable("BoughtFYP", (string)null);
                });

            modelBuilder.Entity("BridgeITAPIs.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Business")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("business");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__Company__3213E83F9B7417C7");

                    b.ToTable("Company", (string)null);
                });

            modelBuilder.Entity("BridgeITAPIs.Models.DegreeReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Achievements")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Activities")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("Gpa")
                        .HasColumnType("float");

                    b.Property<string>("Program")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("program");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("PK__DegreeRe__3213E83FC391FF5B");

                    b.HasIndex("StudentId");

                    b.ToTable("DegreeReport", (string)null);
                });

            modelBuilder.Entity("BridgeITAPIs.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Department1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("department");

                    b.HasKey("Id")
                        .HasName("PK__Departme__3213E83F8B496504");

                    b.ToTable("Department", (string)null);
                });

            modelBuilder.Entity("BridgeITAPIs.Models.EductionalResource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<Guid>("FacultyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("faculty_id");

                    b.Property<string>("SourceLink")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("source_link");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PK__Educatio__3213E83FC3E922D5");

                    b.HasIndex("FacultyId");

                    b.ToTable("EducationalResource", (string)null);
                });

            modelBuilder.Entity("BridgeITAPIs.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EventDate")
                        .HasColumnType("datetime")
                        .HasColumnName("event_date");

                    b.Property<Guid?>("FacultyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("faculty_id");

                    b.Property<string>("SpeakerName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("speaker_name");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("Venue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("venue");

                    b.HasKey("Id")
                        .HasName("PK__Event__3213E83F73A8ACC8");

                    b.HasIndex("FacultyId");

                    b.ToTable("Event", (string)null);
                });

            modelBuilder.Entity("BridgeITAPIs.Models.Faculty", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("department");

                    b.Property<string>("Interest")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("interest");

                    b.Property<string>("Post")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("post");

                    b.Property<Guid?>("UniId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("uni_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__Faculty__3213E83F3ED2B942");

                    b.HasIndex("UniId");

                    b.HasIndex("UserId");

                    b.ToTable("Faculty", (string)null);
                });

            modelBuilder.Entity("BridgeITAPIs.Models.FacultyExperience", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("company_id");

                    b.Property<string>("Duration")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("duration");

                    b.Property<Guid?>("FacultyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("faculty_id");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Job_title");

                    b.Property<string>("Responsibilities")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__FacultyE__3213E83F6FF1BC07");

                    b.HasIndex("CompanyId");

                    b.HasIndex("FacultyId");

                    b.ToTable("FacultyExperience", (string)null);
                });

            modelBuilder.Entity("BridgeITAPIs.Models.FieldOfInterest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("FieldOfInterest1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("field_of_interest");

                    b.HasKey("Id")
                        .HasName("PK__FieldOfI__3213E83F670D4F91");

                    b.ToTable("FieldOfInterest", (string)null);
                });

            modelBuilder.Entity("BridgeITAPIs.Models.ForgotPasswordOtp", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<int>("otp")
                        .HasColumnType("int")
                        .HasColumnName("otp");

                    b.HasKey("id")
                        .HasName("PK__ForgotPa__3213E83F71F90E17");

                    b.ToTable("ForgotPasswordOtp", (string)null);
                });

            modelBuilder.Entity("BridgeITAPIs.Models.Fyp", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Batch")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("batch");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<Guid?>("FacultyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("faculty_id");

                    b.Property<int?>("Members")
                        .HasColumnType("int")
                        .HasColumnName("members");

                    b.Property<string>("Status")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("status");

                    b.Property<string>("Technology")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("technology");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<int?>("YearOfCompletion")
                        .HasColumnType("int")
                        .HasColumnName("year_of_completion");

                    b.Property<string>("fyp_id")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("fyp_id");

                    b.HasKey("Id")
                        .HasName("PK__FYP__3213E83F8A77B011");

                    b.HasIndex("FacultyId");

                    b.ToTable("FYP", (string)null);
                });

            modelBuilder.Entity("BridgeITAPIs.Models.FypMeeting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ChosenSlot")
                        .HasColumnType("datetime2")
                        .HasColumnName("chosen_slot");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("feedback");

                    b.Property<Guid>("FypId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fyp_id");

                    b.Property<Guid>("IndExpId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ind_exp_id");

                    b.Property<bool>("IsMeetDone")
                        .HasColumnType("bit")
                        .HasColumnName("is_meet_done");

                    b.Property<string>("MeetLink")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("meet_link");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("PK__FypMeeti__3213E83F1DF49EAE");

                    b.HasIndex("FypId");

                    b.HasIndex("IndExpId");

                    b.ToTable("FypMeeting", (string)null);
                });

            modelBuilder.Entity("BridgeITAPIs.Models.Idea", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<Guid?>("FacultyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("faculty_id");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Technology")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("technology");

                    b.HasKey("Id")
                        .HasName("PK__Idea__3213E83FFDEF3EB1");

                    b.HasIndex("FacultyId");

                    b.ToTable("Idea", (string)null);
                });

            modelBuilder.Entity("BridgeITAPIs.Models.IndustryExpert", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("company_id");

                    b.Property<string>("Contact")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("contact");

                    b.Property<string>("Post")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("post");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__Industry__3213E83FA9545AA2");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("IndustryExpert", (string)null);
                });

            modelBuilder.Entity("BridgeITAPIs.Models.InterestedForIdea", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("IdeaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idea_id");

                    b.Property<string>("MeetPlace")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("meet_place");

                    b.Property<DateTime?>("MeetTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("MeetTime");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("PK__Interest__3213E83FF623C2C6");

                    b.HasIndex("IdeaId");

                    b.HasIndex("StudentId");

                    b.ToTable("InterestedForIdea", (string)null);
                });

            modelBuilder.Entity("BridgeITAPIs.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("content");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("recipient_id");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sender_id");

                    b.Property<DateTime>("TimeSent")
                        .HasColumnType("datetime2")
                        .HasColumnName("time_stamp");

                    b.HasKey("Id")
                        .HasName("PK__Message__3213E83F25D4FD14");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("BridgeITAPIs.Models.MileStone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("AchievementDate")
                        .HasColumnType("date")
                        .HasColumnName("achievement_date");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("project_id");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PK__MileSton__3213E83F3971CE7B");

                    b.HasIndex("ProjectId");

                    b.ToTable("MileStone", (string)null);
                });

            modelBuilder.Entity("BridgeITAPIs.Models.MilestoneComment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("datetime")
                        .HasColumnName("comment_date");

                    b.Property<Guid>("Commenter_id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("commenter_id");

                    b.Property<Guid>("Milestone_id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("milestone_id");

                    b.HasKey("Id")
                        .HasName("PK__Mileston__3213E83F7B39521F");

                    b.HasIndex("Commenter_id");

                    b.HasIndex("Milestone_id");

                    b.ToTable("MilestoneComment", (string)null);
                });

            modelBuilder.Entity("BridgeITAPIs.Models.Otp", b =>
                {
                    b.Property<string>("email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<DateTime>("created_at")
                        .HasMaxLength(255)
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("otp")
                        .HasColumnType("int")
                        .HasColumnName("otp");

                    b.HasKey("email")
                        .HasName("PK__Otp__AB6E616532361977");

                    b.ToTable("Otp", (string)null);
                });

            modelBuilder.Entity("BridgeITAPIs.Models.PaymentDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("paid_at");

                    b.Property<byte[]>("PaymentSlip")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("payment_slip");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("PK__PaymentD__3213E83F79822DA9");

                    b.HasIndex("ProjectId")
                        .IsUnique()
                        .HasDatabaseName("UQ_PaymentDetail_ProjectId");

                    b.ToTable("PaymentDetail", (string)null);
                });

            modelBuilder.Entity("BridgeITAPIs.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int?>("Budget")
                        .HasColumnType("int")
                        .HasColumnName("budget");

                    b.Property<string>("CurrentStatus")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("current_status");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid?>("FacultyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("faculty_id");

                    b.Property<Guid?>("IndExpertId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ind_expert_id");

                    b.Property<string>("Link")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("link");

                    b.Property<string>("Stack")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("stack");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("student_id");

                    b.Property<int?>("Team")
                        .HasColumnType("int")
                        .HasColumnName("team");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PK__Project__3213E83F9E55023D");

                    b.HasIndex("FacultyId");

                    b.HasIndex("IndExpertId");

                    b.HasIndex("StudentId");

                    b.ToTable("Project", (string)null);
                });

            modelBuilder.Entity("BridgeITAPIs.Models.ProjectImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ImageData")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("image_data");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("PK__ProjectI__3213E83FFE4CB032");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectImages");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.ProjectModule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("project_id");

                    b.Property<bool?>("Status")
                        .HasColumnType("BIT")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("PK__ProjectM__3213E83F17D82272");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectModule", (string)null);
                });

            modelBuilder.Entity("BridgeITAPIs.Models.ProjectProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("description");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("task");

                    b.Property<string>("TaskStatus")
                        .IsRequired()
                        .HasColumnType("VARCHAR(25)")
                        .HasColumnName("task_status");

                    b.HasKey("Id")
                        .HasName("PK__ProjectP__3213E83FDFBC58FE");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectProgress", (string)null);
                });

            modelBuilder.Entity("BridgeITAPIs.Models.ProjectProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("PaymentIntentId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("payment_intent_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("project_id");

                    b.Property<byte[]>("Proposal")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("proposal");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("PK_ProjectProposal");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StudentId");

                    b.ToTable("ProjectProposal", (string)null);
                });

            modelBuilder.Entity("BridgeITAPIs.Models.RequestForFyp", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("FypId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fyp_id");

                    b.Property<Guid>("IndustryExpertId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ind_exp_id");

                    b.Property<int?>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("PK__RequestF__3213E83F08D70405");

                    b.HasIndex("FypId");

                    b.HasIndex("IndustryExpertId");

                    b.HasIndex("StudentId");

                    b.ToTable("RequestForFyp", (string)null);
                });

            modelBuilder.Entity("BridgeITAPIs.Models.RequestForProjectCompletion", b =>
                {
                    b.Property<Guid>("id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("project_id");

                    b.Property<string>("RequestStatus")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(25)")
                        .HasColumnName("request_status");

                    b.HasKey("id")
                        .HasName("PK__RequestT__3213E83F1896BB7E");

                    b.HasIndex("ProjectId");

                    b.ToTable("RequestToCompletePRoject", (string)null);
                });

            modelBuilder.Entity("BridgeITAPIs.Models.ResearchWork", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("category");

                    b.Property<Guid?>("FacultyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("faculty_id");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("link");

                    b.Property<string>("OtherResearchers")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("other_researchers");

                    b.Property<string>("PaperName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paperName");

                    b.Property<string>("PublishChannel")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("publish_channel");

                    b.Property<DateOnly?>("YearOfPublish")
                        .HasColumnType("date")
                        .HasColumnName("year_of_publish");

                    b.HasKey("Id")
                        .HasName("PK__Research__3213E83F4DE5E04E");

                    b.HasIndex("FacultyId");

                    b.ToTable("ResearchWork", (string)null);
                });

            modelBuilder.Entity("BridgeITAPIs.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DatePosted")
                        .HasColumnType("datetime")
                        .HasColumnName("date_posted");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("project_id");

                    b.Property<int?>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<string>("Review1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("review");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reviewer_id");

                    b.HasKey("Id")
                        .HasName("PK__Review__3213E83F560D307B");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("BridgeITAPIs.Models.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Skill1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("skill");

                    b.HasKey("Id")
                        .HasName("PK__Skill__3213E83F62CDF175");

                    b.ToTable("Skill", (string)null);
                });

            modelBuilder.Entity("BridgeITAPIs.Models.SponsoredFyp", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<byte[]>("Agreement")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("agreement");

                    b.Property<Guid?>("FypId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fyp_id");

                    b.Property<Guid?>("SponsoredById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sponsored_by_id");

                    b.HasKey("Id")
                        .HasName("PK__Sponsore__3213E83F08D49FDF");

                    b.HasIndex("FypId");

                    b.HasIndex("SponsoredById");

                    b.ToTable("SponsoredFYP", (string)null);
                });

            modelBuilder.Entity("BridgeITAPIs.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("FypId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fyp_id");

                    b.Property<int?>("RollNumber")
                        .HasColumnType("int")
                        .HasColumnName("rollNumber");

                    b.Property<string>("StripeConnectId")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("stripe_connect_id");

                    b.Property<Guid?>("UniversityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("university_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<string>("cvLink")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("cv_link");

                    b.Property<string>("department")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("department");

                    b.Property<string>("skills")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Skills");

                    b.HasKey("Id")
                        .HasName("PK__Student__3213E83FA8A3DFA8");

                    b.HasIndex("FypId");

                    b.HasIndex("UniversityId");

                    b.HasIndex("UserId");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("BridgeITAPIs.Models.University", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("EstYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<byte[]>("uniImage")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("uniImage");

                    b.HasKey("Id")
                        .HasName("PK__Universi__3213E83FC4E1BD04");

                    b.ToTable("University", (string)null);
                });

            modelBuilder.Entity("BridgeITAPIs.Models.UniversityAdmin", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Contact")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("contact");

                    b.Property<string>("OfficeAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("officeAddress");

                    b.Property<Guid?>("UniId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("uni_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__Universi__3213E83FDD7E6C0B");

                    b.HasIndex("UniId");

                    b.HasIndex("UserId");

                    b.ToTable("UniversityAdmin", (string)null);
                });

            modelBuilder.Entity("BridgeITAPIs.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("firstName");

                    b.Property<string>("Hash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("hash");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("imageData");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("lastName");

                    b.Property<string>("Role")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("role");

                    b.Property<string>("Salt")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("salt");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("otpCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("otpCcode");

                    b.Property<DateTime?>("otpCreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("otpCreatedAt");

                    b.Property<DateTime?>("otpExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("otpExpiresAt");

                    b.Property<int?>("otpType")
                        .HasColumnType("int")
                        .HasColumnName("otpType");

                    b.HasKey("Id")
                        .HasName("PK__User__3213E83F4697F9C5");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("BridgeITAPIs.Models.BoughtFyp", b =>
                {
                    b.HasOne("BridgeITAPIs.Models.Fyp", "Fyp")
                        .WithMany("BoughtFyps")
                        .HasForeignKey("FypId")
                        .HasConstraintName("FK__BoughtFYP__fyp_i__25518C17");

                    b.HasOne("BridgeITAPIs.Models.IndustryExpert", "IndExpert")
                        .WithMany("BoughtFyps")
                        .HasForeignKey("IndExpertId")
                        .HasConstraintName("FK__BoughtFYP__ind_e__2645B050");

                    b.HasOne("BridgeITAPIs.Models.UniversityAdmin", "UniversityAdmin")
                        .WithMany("BoughtFyps")
                        .HasForeignKey("UniversityAdminId")
                        .HasConstraintName("FK__BoughtFYP__unive__2739D489");

                    b.Navigation("Fyp");

                    b.Navigation("IndExpert");

                    b.Navigation("UniversityAdmin");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.DegreeReport", b =>
                {
                    b.HasOne("BridgeITAPIs.Models.Student", "Student")
                        .WithMany("DegreeReports")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__DegreeRep__stude__18EBB532");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.EductionalResource", b =>
                {
                    b.HasOne("BridgeITAPIs.Models.Faculty", "Faculty")
                        .WithMany("EducationalResources")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Education__facul__756D6ECB");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.Event", b =>
                {
                    b.HasOne("BridgeITAPIs.Models.Faculty", "Faculty")
                        .WithMany("Events")
                        .HasForeignKey("FacultyId")
                        .HasConstraintName("FK__Event__faculty_i__1CBC4616");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.Faculty", b =>
                {
                    b.HasOne("BridgeITAPIs.Models.University", "Uni")
                        .WithMany("Faculties")
                        .HasForeignKey("UniId")
                        .HasConstraintName("FK__Faculty__uni_id__160F4887");

                    b.HasOne("BridgeITAPIs.Models.User", "User")
                        .WithMany("Faculties")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Faculty__user_id__151B244E");

                    b.Navigation("Uni");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.FacultyExperience", b =>
                {
                    b.HasOne("BridgeITAPIs.Models.Company", "Company")
                        .WithMany("FacultyExperiences")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("FK__FacultyEx__compa__1AD3FDA4");

                    b.HasOne("BridgeITAPIs.Models.Faculty", "Faculty")
                        .WithMany("FacultyExperiences")
                        .HasForeignKey("FacultyId")
                        .HasConstraintName("FK__FacultyEx__facul__19DFD96B");

                    b.Navigation("Company");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.Fyp", b =>
                {
                    b.HasOne("BridgeITAPIs.Models.Faculty", "Faculty")
                        .WithMany("Fyps")
                        .HasForeignKey("FacultyId")
                        .HasConstraintName("FK__FYP__faculty_id__65F62111");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.FypMeeting", b =>
                {
                    b.HasOne("BridgeITAPIs.Models.Fyp", "Fyp")
                        .WithMany("FypMeetings")
                        .HasForeignKey("FypId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__FypMeetin__fyp_i__1B9317B3");

                    b.HasOne("BridgeITAPIs.Models.IndustryExpert", "IndustryExpert")
                        .WithMany("FypMeetings")
                        .HasForeignKey("IndExpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__FypMeetin__ind_e__1C873BEC");

                    b.Navigation("Fyp");

                    b.Navigation("IndustryExpert");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.Idea", b =>
                {
                    b.HasOne("BridgeITAPIs.Models.Faculty", "Faculty")
                        .WithMany("Ideas")
                        .HasForeignKey("FacultyId")
                        .HasConstraintName("FK__Idea__faculty_id__1DB06A4F");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.IndustryExpert", b =>
                {
                    b.HasOne("BridgeITAPIs.Models.Company", "Company")
                        .WithMany("IndustryExperts")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("FK__IndustryE__compa__17F790F9");

                    b.HasOne("BridgeITAPIs.Models.User", "User")
                        .WithMany("IndustryExperts")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__IndustryE__user___17036CC0");

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.InterestedForIdea", b =>
                {
                    b.HasOne("BridgeITAPIs.Models.Idea", "Idea")
                        .WithMany("InterestedForIdeas")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__InterestedForIdea_Idea");

                    b.HasOne("BridgeITAPIs.Models.Student", "Student")
                        .WithMany("InterestedForIdeas")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__InterestedForIdea_Student");

                    b.Navigation("Idea");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.MileStone", b =>
                {
                    b.HasOne("BridgeITAPIs.Models.Project", "Project")
                        .WithMany("MileStones")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("FK__MileStone__proje__208CD6FA");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.MilestoneComment", b =>
                {
                    b.HasOne("BridgeITAPIs.Models.IndustryExpert", "Commenter")
                        .WithMany("MilestoneComments")
                        .HasForeignKey("Commenter_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Milestone__comme__2EA5EC27");

                    b.HasOne("BridgeITAPIs.Models.MileStone", "MileStone")
                        .WithMany("MilestoneComments")
                        .HasForeignKey("Milestone_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Milestone__miles_2F9A1060");

                    b.Navigation("Commenter");

                    b.Navigation("MileStone");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.PaymentDetail", b =>
                {
                    b.HasOne("BridgeITAPIs.Models.Project", "Project")
                        .WithOne("PaymentDetail")
                        .HasForeignKey("BridgeITAPIs.Models.PaymentDetail", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__PaymentDe__proje__625A9A57");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.Project", b =>
                {
                    b.HasOne("BridgeITAPIs.Models.Faculty", "Faculty")
                        .WithMany("Projects")
                        .HasForeignKey("FacultyId")
                        .HasConstraintName("FK_Project_Faculty");

                    b.HasOne("BridgeITAPIs.Models.IndustryExpert", "IndExpert")
                        .WithMany("Projects")
                        .HasForeignKey("IndExpertId")
                        .HasConstraintName("FK__Project__ind_exp__1F98B2C1");

                    b.HasOne("BridgeITAPIs.Models.Student", "Student")
                        .WithMany("Projects")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__Project__student__1EA48E88");

                    b.Navigation("Faculty");

                    b.Navigation("IndExpert");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.ProjectImage", b =>
                {
                    b.HasOne("BridgeITAPIs.Models.Project", "Project")
                        .WithMany("ProjectImages")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("FK__ProjectIm__proje__236943A5");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.ProjectModule", b =>
                {
                    b.HasOne("BridgeITAPIs.Models.Project", "Project")
                        .WithMany("Modules")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ProjectMo__proje__2EA5EC27");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.ProjectProgress", b =>
                {
                    b.HasOne("BridgeITAPIs.Models.Project", "Project")
                        .WithMany("ProjectProgresses")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ProjectPr__proje__3C34F16F");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.ProjectProposal", b =>
                {
                    b.HasOne("BridgeITAPIs.Models.Project", "Project")
                        .WithMany("Proposals")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ProjectProposal_Project");

                    b.HasOne("BridgeITAPIs.Models.Student", "Student")
                        .WithMany("Proposals")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ProjectProposal_Student");

                    b.Navigation("Project");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.RequestForFyp", b =>
                {
                    b.HasOne("BridgeITAPIs.Models.Fyp", "Fyp")
                        .WithMany("RequestForFyps")
                        .HasForeignKey("FypId")
                        .IsRequired()
                        .HasConstraintName("FK__FOR_FYP");

                    b.HasOne("BridgeITAPIs.Models.IndustryExpert", "IndustryExpert")
                        .WithMany("RequestForFyps")
                        .HasForeignKey("IndustryExpertId")
                        .IsRequired()
                        .HasConstraintName("FK__RequestFo__ind_e__0697FACD");

                    b.HasOne("BridgeITAPIs.Models.Student", "Student")
                        .WithMany("RequestForFyps")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__Requested_Student");

                    b.Navigation("Fyp");

                    b.Navigation("IndustryExpert");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.RequestForProjectCompletion", b =>
                {
                    b.HasOne("BridgeITAPIs.Models.Project", "project")
                        .WithMany("requestForProjectCompletions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__RequestTo__proje__4F47C5E3");

                    b.Navigation("project");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.ResearchWork", b =>
                {
                    b.HasOne("BridgeITAPIs.Models.Faculty", "Faculty")
                        .WithMany("ResearchWorks")
                        .HasForeignKey("FacultyId")
                        .HasConstraintName("FK__ResearchW__facul__1BC821DD");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.Review", b =>
                {
                    b.HasOne("BridgeITAPIs.Models.Project", "Project")
                        .WithMany("Reviews")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("FK__Review__project___2180FB33");

                    b.HasOne("BridgeITAPIs.Models.User", "Reviewer")
                        .WithMany("Reviews")
                        .HasForeignKey("ReviewerId")
                        .HasConstraintName("FK__Review__reviewer__22751F6C");

                    b.Navigation("Project");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.SponsoredFyp", b =>
                {
                    b.HasOne("BridgeITAPIs.Models.Fyp", "Fyp")
                        .WithMany("SponsoredFyps")
                        .HasForeignKey("FypId")
                        .HasConstraintName("FK__Sponsored__fyp_i__282DF8C2");

                    b.HasOne("BridgeITAPIs.Models.IndustryExpert", "SponsoredBy")
                        .WithMany("SponsoredFyps")
                        .HasForeignKey("SponsoredById")
                        .HasConstraintName("FK__Sponsored__spons__29221CFB");

                    b.Navigation("Fyp");

                    b.Navigation("SponsoredBy");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.Student", b =>
                {
                    b.HasOne("BridgeITAPIs.Models.Fyp", "Fyp")
                        .WithMany("Students")
                        .HasForeignKey("FypId")
                        .HasConstraintName("FK__Student_FYP");

                    b.HasOne("BridgeITAPIs.Models.University", "University")
                        .WithMany("Students")
                        .HasForeignKey("UniversityId")
                        .HasConstraintName("FK__Student__univers__1332DBDC");

                    b.HasOne("BridgeITAPIs.Models.User", "User")
                        .WithMany("Students")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Student__user_id__14270015");

                    b.Navigation("Fyp");

                    b.Navigation("University");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.UniversityAdmin", b =>
                {
                    b.HasOne("BridgeITAPIs.Models.University", "Uni")
                        .WithMany("UniversityAdmins")
                        .HasForeignKey("UniId")
                        .HasConstraintName("FK__Universit__uni_i__123EB7A3");

                    b.HasOne("BridgeITAPIs.Models.User", "User")
                        .WithMany("UniversityAdmins")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Universit__user___114A936A");

                    b.Navigation("Uni");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.Company", b =>
                {
                    b.Navigation("FacultyExperiences");

                    b.Navigation("IndustryExperts");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.Faculty", b =>
                {
                    b.Navigation("EducationalResources");

                    b.Navigation("Events");

                    b.Navigation("FacultyExperiences");

                    b.Navigation("Fyps");

                    b.Navigation("Ideas");

                    b.Navigation("Projects");

                    b.Navigation("ResearchWorks");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.Fyp", b =>
                {
                    b.Navigation("BoughtFyps");

                    b.Navigation("FypMeetings");

                    b.Navigation("RequestForFyps");

                    b.Navigation("SponsoredFyps");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.Idea", b =>
                {
                    b.Navigation("InterestedForIdeas");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.IndustryExpert", b =>
                {
                    b.Navigation("BoughtFyps");

                    b.Navigation("FypMeetings");

                    b.Navigation("MilestoneComments");

                    b.Navigation("Projects");

                    b.Navigation("RequestForFyps");

                    b.Navigation("SponsoredFyps");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.MileStone", b =>
                {
                    b.Navigation("MilestoneComments");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.Project", b =>
                {
                    b.Navigation("MileStones");

                    b.Navigation("Modules");

                    b.Navigation("PaymentDetail");

                    b.Navigation("ProjectImages");

                    b.Navigation("ProjectProgresses");

                    b.Navigation("Proposals");

                    b.Navigation("Reviews");

                    b.Navigation("requestForProjectCompletions");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.Student", b =>
                {
                    b.Navigation("DegreeReports");

                    b.Navigation("InterestedForIdeas");

                    b.Navigation("Projects");

                    b.Navigation("Proposals");

                    b.Navigation("RequestForFyps");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.University", b =>
                {
                    b.Navigation("Faculties");

                    b.Navigation("Students");

                    b.Navigation("UniversityAdmins");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.UniversityAdmin", b =>
                {
                    b.Navigation("BoughtFyps");
                });

            modelBuilder.Entity("BridgeITAPIs.Models.User", b =>
                {
                    b.Navigation("Faculties");

                    b.Navigation("IndustryExperts");

                    b.Navigation("Reviews");

                    b.Navigation("Students");

                    b.Navigation("UniversityAdmins");
                });
#pragma warning restore 612, 618
        }
    }
}
